select   B.TITLE,B.BOARD_ID,R.REPLY_ID,R.WRITER_ID,R.CONTENTS
        ,DATE_FORMAT(R.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
from    USED_GOODS_BOARD as B
join    USED_GOODS_REPLY as R
on      B.BOARD_ID = R.BOARD_ID
WHERE MONTH(B.CREATED_DATE) = 10
order by R.CREATED_DATE asc ,B.TITLE asc