SELECT B.WRITER_ID, U.NICKNAME, B.TOTAL_SALES
FROM USED_GOODS_USER AS U
JOIN (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = "DONE"
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
) AS B
WHERE B.WRITER_ID = U.USER_ID
ORDER BY B.TOTAL_SALES;
